# Generated by Django 5.1.4 on 2025-08-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_userkyc_delete_user_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkyc',
            old_name='aadhaar_client_id',
            new_name='digilocker_client_id',
        ),
        migrations.RemoveField(
            model_name='userkyc',
            name='dl_client_id',
        ),
        migrations.RemoveField(
            model_name='userkyc',
            name='pan_client_id',
        ),
    ]
