# Generated by Django 5.1.4 on 2025-08-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_aadhaar_client_id_userkyc_digilocker_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkyc',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
