# Generated by Django 5.1.4 on 2025-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_approved_userkyc_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='dl_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/driving_license/'),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/pan/'),
        ),
    ]
