# Generated by Django 5.1.4 on 2025-09-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userkyc_dl_file_userkyc_pan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='adhar_image_file',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/pan/'),
        ),
    ]
