# Generated by Django 5.1.4 on 2025-06-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_kyc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kyc',
            new_name='user_kyc',
        ),
    ]
