# Generated by Django 5.1.4 on 2025-06-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Vendor_for_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parcel_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_price_worth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('pickup_address_line1', models.CharField(max_length=255)),
                ('pickup_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_contact', models.CharField(max_length=20)),
                ('destination_address_line1', models.CharField(max_length=255)),
                ('destination_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_pincode', models.CharField(max_length=10)),
                ('destination_state', models.CharField(max_length=100)),
                ('destination_contact', models.CharField(max_length=20)),
                ('legal_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='masters.city')),
                ('pickup_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_city', to='masters.city')),
            ],
        ),
    ]
