# Generated by Django 5.1.4 on 2025-06-15 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_vendor_for_delivery',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='request_vendor_for_delivery',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.trip'),
        ),
        migrations.AddField(
            model_name='request_vendor_for_delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
