# Generated by Django 5.1.4 on 2025-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_vendor_for_delivery',
            name='request_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop')], default='pickup', max_length=20),
        ),
    ]
