# Generated by Django 5.1.4 on 2025-06-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_request_vendor_for_delivery_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='request_vendor_for_delivery',
            name='tracking_id',
        ),
    ]
