# Generated by Django 5.1.4 on 2025-06-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='is_agent_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
