# Generated by Django 5.1.4 on 2025-06-13 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_scamcomplaint_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamproof',
            name='complaint',
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parcel_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_price_worth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('pickup_address_line1', models.CharField(max_length=255)),
                ('pickup_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_pincode', models.CharField(max_length=10)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_contact', models.CharField(max_length=20)),
                ('destination_address_line1', models.CharField(max_length=255)),
                ('destination_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_pincode', models.CharField(max_length=10)),
                ('destination_state', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_contact', models.CharField(max_length=20)),
                ('legal_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ScamComplaint',
        ),
        migrations.DeleteModel(
            name='ScamProof',
        ),
    ]
