# Generated by Django 5.1.4 on 2025-06-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_scamproof_complaint_deliveryrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_city',
        ),
    ]
