# Generated by Django 5.1.4 on 2025-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_deliveryrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_vendor_for_delivery',
            name='request_type',
            field=models.CharField(choices=[('self_drop', 'Self Drop'), ('home_pickup', 'Home Pickup'), ('home_drop', 'Home Drop'), ('self_pickup', 'Self Pickup')], default='pickup', max_length=20),
        ),
    ]
