# Generated by Django 5.1.4 on 2025-06-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_deliveryrequest_destination_city_and_more'),
        ('masters', '0008_rename_occupation_category_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='masters.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_city', to='masters.city'),
            preserve_default=False,
        ),
    ]
