# Generated by Django 5.1.4 on 2025-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_request_vendor_for_delivery_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='request_vendor_for_delivery',
            name='request_type',
        ),
        migrations.AddField(
            model_name='request_vendor_for_delivery',
            name='request_type',
            field=models.ManyToManyField(to='customer.requesttype'),
        ),
    ]
