# Generated by Django 5.1.4 on 2025-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_requesttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_vendor_for_delivery',
            name='request_type',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='request_type',
            field=models.ManyToManyField(to='customer.requesttype'),
        ),
    ]
