# Generated by Django 5.1.4 on 2025-06-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_order_agent_customer_order_assigned_at_and_more'),
        ('masters', '0002_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='destination_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='masters.city'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='destination_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='destination_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='destination_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_city', to='masters.city'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
