# Generated by Django 5.1.4 on 2025-06-21 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_deliveryrequest_destination_address_line1_and_more'),
        ('vendor', '0007_alter_request_customer_for_delivery_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='agent',
        ),
        migrations.AddField(
            model_name='customer_order',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor.trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled_by_vendor', 'Cancelled By Vendor'), ('cancelled_by_customer', 'Cancelled By Customer')], default='assigned', max_length=50),
        ),
    ]
