# Generated by Django 5.1.4 on 2025-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_customer_order_agent_customer_order_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_vendor_for_delivery',
            name='request_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request_vendor_for_delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected_by_vendor', 'Rejected By Vendor'), ('rejected_by_customer', 'Rejected By Customer'), ('cancelled_by_customer', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
