# Generated by Django 5.1.4 on 2025-06-25 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_request_vendor_for_delivery_request_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_vendor_for_delivery',
            old_name='request_price',
            new_name='requested_price',
        ),
    ]
