# Generated by Django 5.1.4 on 2025-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_rename_request_price_request_vendor_for_delivery_requested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_vendor_for_delivery',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
