# Generated by Django 5.1.4 on 2025-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_request_vendor_for_delivery_requested_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='connection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
