# Generated by Django 5.1.4 on 2025-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_deliveryrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delivered_by_customer', 'Delivered By Customer'), ('cancelled_by_vendor', 'Cancelled By Vendor'), ('cancelled_by_customer', 'Cancelled By Customer')], default='assigned', max_length=50),
        ),
    ]
