# Generated by Django 5.1.4 on 2025-07-01 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer_order'),
            preserve_default=False,
        ),
    ]
