# Generated by Django 5.1.4 on 2025-07-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_supportticket_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='issue_type',
        ),
    ]
