# Generated by Django 5.1.4 on 2025-07-01 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_remove_supportticket_issue_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliveryrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsd', to='customer.customer_order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deliveryrating',
            unique_together={('vendor', 'user', 'shipment')},
        ),
    ]
