# Generated by Django 5.1.4 on 2025-07-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_deliveryrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
