# Generated by Django 5.1.4 on 2025-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_customer_order_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
    ]
