# Generated by Django 5.1.4 on 2025-08-16 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_paymentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('yob', models.CharField(blank=True, max_length=4, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='aadhaar_photos/')),
                ('masked_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_json', models.JSONField(blank=True, null=True)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
