# Generated by Django 5.1.4 on 2025-11-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_aadhaardetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='destination_address_line1',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='destination_address_line2',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='destination_pincode',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='destination_state',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_address_line1',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_address_line2',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_city',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_pincode',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_state',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_formatted_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_formatted_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VendorLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='customer.customer_order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
