# Generated by Django 5.1.4 on 2025-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_remove_deliveryrequest_destination_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_drop_pickup_address_line1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_drop_pickup_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_drop_pickup_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_drop_pickup_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_drop_pickup_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_pickup_address_line1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_pickup_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_pickup_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_pickup_pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='home_pickup_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
