# Generated by Django 5.1.4 on 2025-12-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_deliveryrequest_home_drop_pickup_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_pickup_address_line1',
            new_name='home_drop_address_line1',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_pickup_address_line2',
            new_name='home_drop_address_line2',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_pickup_contact',
            new_name='home_drop_contact',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_pickup_pincode',
            new_name='home_drop_pincode',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_pickup_state',
            new_name='home_drop_state',
        ),
    ]
