# Generated by Django 5.1.4 on 2025-12-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_rename_home_drop_pickup_address_line1_deliveryrequest_home_drop_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_pincode',
            new_name='destination_pincode',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_drop_state',
            new_name='destination_state_name',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_pickup_pincode',
            new_name='pickup_pincode',
        ),
        migrations.RenameField(
            model_name='deliveryrequest',
            old_name='home_pickup_state',
            new_name='pickup_state_name',
        ),
    ]
