# Generated by Django 5.1.4 on 2025-12-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_rename_home_drop_pincode_deliveryrequest_destination_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='home_drop_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='home_pickup_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
