# Generated by Django 5.1.4 on 2026-03-15 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_product_request_vendor_for_product'),
        ('vendor', '0014_request_customer_for_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_vendor_for_product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted_by_vendor', 'Vendor Accepted'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('delivered_by_customer', 'Delivered By Customer'), ('rejected_by_vendor', 'Rejected By Vendor'), ('rejected_by_customer', 'Rejected By Customer'), ('cancelled_by_customer', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Customer_Product_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delivered_by_customer', 'Delivered By Customer'), ('cancelled_by_vendor', 'Cancelled By Vendor'), ('cancelled_by_customer', 'Cancelled By Customer')], default='assigned', max_length=50)),
                ('connection_id', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
