# Generated by Django 5.1.4 on 2026-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_productdeliveryrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardetails',
            name='client_id',
            field=models.CharField(max_length=500),
        ),
    ]
