# Generated by Django 5.1.4 on 2025-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_occupation_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='occupation_category',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='occupation_subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='ScamCategory',
        ),
        migrations.DeleteModel(
            name='occupation',
        ),
        migrations.DeleteModel(
            name='occupation_subcategory',
        ),
    ]
